### ISSUE TITLE
Add fullscreen support to <leaflet-map>

### ISSUE THREAD

**Issue by shgysk8zer0** [shgysk8zer0/cdn.kernvalley.us#170]
### Screenshot
![image](https://user-images.githubusercontent.com/1627459/86056538-78f94080-ba12-11ea-903c-d16bacb17beb.png)

The following CSS seems to do the trick:
```css
:host(:fullscreen) ::slotted([slot="map"]), :host(:fullscreen) #map-fallback {
	height: 100vh;
	width: 100vw;
}
```
